-- MySQL Script generated by MySQL Workbench
-- 03/04/16 16:27:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sat` DEFAULT CHARACTER SET utf8 ;
USE `sat` ;

-- -----------------------------------------------------
-- Table `sat`.`Mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Mahasiswa` (
  `nim` VARCHAR(20) NOT NULL,
  `nama` VARCHAR(100) NULL,
  `angkatan` INT NULL,
  `no_hp` VARCHAR(12) NULL,
  `email` MEDIUMTEXT NULL,
  `password` VARCHAR(100) NULL,
  `is_deleted_mhs` TINYINT(1) NULL,
  `deleted_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_penutor` TINYINT(1) NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`nim`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Mata_Kuliah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Mata_Kuliah` (
  `id_mk` INT NULL,
  `nama_mk` VARCHAR(100) NULL,
  `is_deleted` TINYINT(1) NULL,
  `deleted_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_mk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Mengajar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Mengajar` (
  `Mahasiswa_nim` VARCHAR(20) NOT NULL,
  `Mata_Kuliah_id_mk` INT NOT NULL,
  PRIMARY KEY (`Mahasiswa_nim`, `Mata_Kuliah_id_mk`),
  INDEX `fk_Mahasiswa_has_Mata_Kuliah_Mahasiswa_idx` (`Mahasiswa_nim` ASC),
  CONSTRAINT `fk_Mahasiswa_has_Mata_Kuliah_Mahasiswa`
    FOREIGN KEY (`Mahasiswa_nim`)
    REFERENCES `sat`.`Mahasiswa` (`nim`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mahasiswa_has_Mata_Kuliah_Mata_Kuliah1`
    FOREIGN KEY ()
    REFERENCES `sat`.`Mata_Kuliah` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Mengambil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Mengambil` (
  `Mahasiswa_nim` VARCHAR(20) NOT NULL,
  `Mata_Kuliah_id_mk` INT NOT NULL,
  `tgl_register` DATETIME(6) NOT NULL,
  `is_over` TINYINT(1) NULL,
  PRIMARY KEY (`Mahasiswa_nim`, `Mata_Kuliah_id_mk`, `tgl_register`),
  INDEX `fk_Mahasiswa_has_Mata_Kuliah_Mata_Kuliah2_idx` (`Mata_Kuliah_id_mk` ASC),
  INDEX `fk_Mahasiswa_has_Mata_Kuliah_Mahasiswa1_idx` (`Mahasiswa_nim` ASC),
  CONSTRAINT `fk_Mahasiswa_has_Mata_Kuliah_Mahasiswa1`
    FOREIGN KEY (`Mahasiswa_nim`)
    REFERENCES `sat`.`Mahasiswa` (`nim`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mahasiswa_has_Mata_Kuliah_Mata_Kuliah2`
    FOREIGN KEY (`Mata_Kuliah_id_mk`)
    REFERENCES `sat`.`Mata_Kuliah` (`id_mk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Absen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Absen` (
  `Mengambil_Mahasiswa_nim` VARCHAR(20) NOT NULL,
  `Mengambil_Mata_Kuliah_id_mk` INT NOT NULL,
  `Mengambil_tgl_register` DATETIME(6) NOT NULL,
  `Mahasiswa_nim` VARCHAR(20) NOT NULL,
  `tgl_absen` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_over_absen` TINYINT(1) NULL,
  PRIMARY KEY (`Mengambil_Mahasiswa_nim`, `Mengambil_Mata_Kuliah_id_mk`, `Mengambil_tgl_register`),
  INDEX `fk_Absen_Mahasiswa1_idx` (`Mahasiswa_nim` ASC),
  CONSTRAINT `fk_Absen_Mengambil1`
    FOREIGN KEY (`Mengambil_Mahasiswa_nim` , `Mengambil_Mata_Kuliah_id_mk` , `Mengambil_tgl_register`)
    REFERENCES `sat`.`Mengambil` (`Mahasiswa_nim` , `Mata_Kuliah_id_mk` , `tgl_register`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Absen_Mahasiswa1`
    FOREIGN KEY (`Mahasiswa_nim`)
    REFERENCES `sat`.`Mahasiswa` (`nim`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
