-- MySQL Script generated by MySQL Workbench
-- 03/04/16 17:23:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sat` DEFAULT CHARACTER SET utf8 ;
USE `sat` ;

-- -----------------------------------------------------
-- Table `sat`.`Mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Mahasiswa` (
  `nim` VARCHAR(20) NOT NULL,
  `nama` VARCHAR(100) NULL,
  `angkatan` INT NULL,
  `no_hp` VARCHAR(12) NULL,
  `email` MEDIUMTEXT NULL,
  `password` VARCHAR(100) NULL,
  `is_deleted_mhs` TINYINT(1) NULL,
  `deleted_at` DATETIME NULL,
  `is_penutor` TINYINT(1) NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`nim`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Mata_Kuliah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Mata_Kuliah` (
  `id_mk` INT NULL,
  `nama_mk` VARCHAR(100) NULL,
  `is_deleted` TINYINT(1) NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id_mk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Mengambil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Mengambil` (
  `Mahasiswa_nim` VARCHAR(20) NOT NULL,
  `Mata_Kuliah_id_mk` INT NOT NULL,
  `tgl_register` DATETIME NOT NULL,
  `is_over` TINYINT(1) NULL,
  PRIMARY KEY (`Mahasiswa_nim`, `Mata_Kuliah_id_mk`, `tgl_register`),
  INDEX `fk_Mahasiswa_has_Mata_Kuliah_Mata_Kuliah2_idx` (`Mata_Kuliah_id_mk` ASC),
  INDEX `fk_Mahasiswa_has_Mata_Kuliah_Mahasiswa1_idx` (`Mahasiswa_nim` ASC),
  CONSTRAINT `fk_Mahasiswa_has_Mata_Kuliah_Mahasiswa1`
    FOREIGN KEY (`Mahasiswa_nim`)
    REFERENCES `sat`.`Mahasiswa` (`nim`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mahasiswa_has_Mata_Kuliah_Mata_Kuliah2`
    FOREIGN KEY (`Mata_Kuliah_id_mk`)
    REFERENCES `sat`.`Mata_Kuliah` (`id_mk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Absen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Absen` (
  `Mengambil_Mahasiswa_nim` VARCHAR(20) NOT NULL,
  `Mengambil_Mata_Kuliah_id_mk` INT NOT NULL,
  `Mengambil_tgl_register` DATETIME(6) NOT NULL,
  `Mahasiswa_nim` VARCHAR(20) NOT NULL,
  `tgl_absen` DATETIME NULL,
  `is_over_absen` TINYINT(1) NULL,
  PRIMARY KEY (`Mengambil_Mahasiswa_nim`, `Mengambil_Mata_Kuliah_id_mk`, `Mengambil_tgl_register`),
  INDEX `fk_Absen_Mahasiswa1_idx` (`Mahasiswa_nim` ASC),
  CONSTRAINT `fk_Absen_Mengambil1`
    FOREIGN KEY (`Mengambil_Mahasiswa_nim` , `Mengambil_Mata_Kuliah_id_mk` , `Mengambil_tgl_register`)
    REFERENCES `sat`.`Mengambil` (`Mahasiswa_nim` , `Mata_Kuliah_id_mk` , `tgl_register`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Absen_Mahasiswa1`
    FOREIGN KEY (`Mahasiswa_nim`)
    REFERENCES `sat`.`Mahasiswa` (`nim`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Penutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Penutor` (
  `Mahasiswa_nim` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Mahasiswa_nim`),
  CONSTRAINT `fk_Penutor_Mahasiswa1`
    FOREIGN KEY (`Mahasiswa_nim`)
    REFERENCES `sat`.`Mahasiswa` (`nim`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Absen_has_Mengambil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Absen_has_Mengambil` (
  `Absen_Mengambil_Mahasiswa_nim` VARCHAR(20) NOT NULL,
  `Absen_Mengambil_Mata_Kuliah_id_mk` INT NOT NULL,
  `Absen_Mengambil_tgl_register` DATETIME(6) NOT NULL,
  `Mengambil_Mahasiswa_nim` VARCHAR(20) NOT NULL,
  `Mengambil_Mata_Kuliah_id_mk` INT NOT NULL,
  `Mengambil_tgl_register` DATETIME NOT NULL,
  PRIMARY KEY (`Absen_Mengambil_Mahasiswa_nim`, `Absen_Mengambil_Mata_Kuliah_id_mk`, `Absen_Mengambil_tgl_register`, `Mengambil_Mahasiswa_nim`, `Mengambil_Mata_Kuliah_id_mk`, `Mengambil_tgl_register`),
  INDEX `fk_Absen_has_Mengambil_Mengambil1_idx` (`Mengambil_Mahasiswa_nim` ASC, `Mengambil_Mata_Kuliah_id_mk` ASC, `Mengambil_tgl_register` ASC),
  INDEX `fk_Absen_has_Mengambil_Absen1_idx` (`Absen_Mengambil_Mahasiswa_nim` ASC, `Absen_Mengambil_Mata_Kuliah_id_mk` ASC, `Absen_Mengambil_tgl_register` ASC),
  CONSTRAINT `fk_Absen_has_Mengambil_Absen1`
    FOREIGN KEY (`Absen_Mengambil_Mahasiswa_nim` , `Absen_Mengambil_Mata_Kuliah_id_mk` , `Absen_Mengambil_tgl_register`)
    REFERENCES `sat`.`Absen` (`Mengambil_Mahasiswa_nim` , `Mengambil_Mata_Kuliah_id_mk` , `Mengambil_tgl_register`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Absen_has_Mengambil_Mengambil1`
    FOREIGN KEY (`Mengambil_Mahasiswa_nim` , `Mengambil_Mata_Kuliah_id_mk` , `Mengambil_tgl_register`)
    REFERENCES `sat`.`Mengambil` (`Mahasiswa_nim` , `Mata_Kuliah_id_mk` , `tgl_register`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sat`.`Mata_Kuliah_has_Penutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sat`.`Mata_Kuliah_has_Penutor` (
  `Mata_Kuliah_id_mk` INT NOT NULL,
  `Penutor_Mahasiswa_nim` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Mata_Kuliah_id_mk`, `Penutor_Mahasiswa_nim`),
  INDEX `fk_Mata_Kuliah_has_Penutor_Penutor1_idx` (`Penutor_Mahasiswa_nim` ASC),
  INDEX `fk_Mata_Kuliah_has_Penutor_Mata_Kuliah1_idx` (`Mata_Kuliah_id_mk` ASC),
  CONSTRAINT `fk_Mata_Kuliah_has_Penutor_Mata_Kuliah1`
    FOREIGN KEY (`Mata_Kuliah_id_mk`)
    REFERENCES `sat`.`Mata_Kuliah` (`id_mk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mata_Kuliah_has_Penutor_Penutor1`
    FOREIGN KEY (`Penutor_Mahasiswa_nim`)
    REFERENCES `sat`.`Penutor` (`Mahasiswa_nim`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
